import {
  Bell,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  Clock,
  CreditCard,
  Download,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Home,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  ListChecks,
  LogOut,
  Menu,
  MessageCircle,
  Pencil,
  Plus,
  RefreshCcw,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Trash2,
  TriangleAlert,
  User,
  Users,
  X,
} from 'lucide-react'

const ICONS = {
  bell: Bell,
  'calendar-clock': CalendarClock,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  currency: CircleDollarSign,
  clock: Clock,
  'credit-card': CreditCard,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  'eye-off': EyeOff,
  file: FileText,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  'layout-dashboard': LayoutDashboard,
  list: ListChecks,
  'log-out': LogOut,
  menu: Menu,
  'message-circle': MessageCircle,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCcw,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  'shopping-bag': ShoppingBag,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  user: User,
  users: Users,
  x: X,
}

export function Icon({ name, className = 'h-5 w-5', size, ...props }) {
  const Cmp = ICONS[name] || Dumbbell
  return <Cmp className={className} size={size} {...props} />
}

export { ICONS }
